services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db_student_portal
      MYSQL_USER: manik_mahardika
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_DSN: manik_mahardika:password@tcp(db:3306)/db_student_portal?parseTime=true&loc=Local
      JWT_SECRET: change-me-please
      JWT_EXPIRES_IN: 24h
      JWT_ISSUER: student-portal
      OLLAMA_BASE_URLS: https://llm.onestepsolutionbali.com,http://160.19.166.60:11434
      OLLAMA_BASE_URL: https://llm.onestepsolutionbali.com
      OLLAMA_MODEL: qwen2.5:3b
      OLLAMA_TIMEOUT_SEC: 300
      AI_GENERATE_TIMEOUT_SEC: 300
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
      - go_mod:/go/pkg/mod
      - go_cache:/root/.cache/go-build
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  go_mod:
  go_cache:
