package schema

// AllModels returns all GORM models for AutoMigrate.
func AllModels() []interface{} {
	return []interface{}{
		&User{},
		&NoteStudent{},
		&DocumentsManagement{},
		&StepsManagement{},
		&ChildStepsManagement{},
		&CountryManagement{},
		&VisaTypeManagement{},
		&StageManagement{},
		&CountryStepsManagement{},
		&ChatConversation{},
		&ChatConversationMember{},
		&ChatMessage{},
		&ChatMessageAttachment{},
		&ChatMessageStatus{},
		&ChatMessageMention{},
		&Question{},
		&QuestionOption{},
		&AnswerQuestion{},
		&AnswerSubmission{},
		&AnswerSelectedOption{},
		&AnswerDocument{},
		&GeneratedCVAIDocument{},
		&GeneratedStatementLetterAIDocument{},
		&StatementLetterAIApproval{},
		&StatementLetterAIApprovalLog{},
		&GeneratedSponsorLetterAIDocument{},
		&SponsorLetterAIApproval{},
		&SponsorLetterAIApprovalLog{},
		&AnswerApproval{},
		&AnswerDocumentApproval{},
		&DocumentTranslation{},
		&QuestionBase{},
		&TicketMessage{},
		&InformationCountryManagement{},
	}
}
